[package]
name = "ChatNexus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]] # Bin to run the HelloWorld gRPC server
name = "ChatNexus-server"
path = "src/server/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "ChatNexus-client"
path = "src/client/client.rs"

[dependencies]
prost = "0.11.8"
tonic = "0.9.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
oauth2 = "4.3.0"
mongodb = "2.4.0"

[build-dependencies]
tonic-build = "0.9.0"
