[package]
name = "ChatNexus"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ChatNexus-Auth"
path = "src/chatnexus-auth/server.rs"

[[bin]]
name = "ChatNexus-Chat"
path = "src/chatnexus-chat/server.rs"

[[bin]]
name = "ChatNexus-Client"
path = "src/chatnexus-client/client.rs"

[dependencies]
prost = "0.11.8"
tonic = "0.9.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.12"
oauth2 = "4.3.0"
mongodb = "2.4.0"

[build-dependencies]
tonic-build = "0.9.0"
